#[connections.postgresql]
#dialect = "postgresql"
#host = "localhost"
#port = "5432"
#database = "avicudatos"
#username = "postgres"
#password = "qwerty"

[database]
#dialect = "postgresql"
host = "localhost"
port = "5432"
database = "avicudatos"
username = "postgres"
password = "qwerty"

#conString = 'postgresql+psycopg://postgres:qwerty@localhost:5432/avicudatos'

[DATABASE_CONFIG]
#dbname: 'avicudatos'
#user: 'postgres'
#password: 'qwerty'
#host: 'localhost'
#port: '5432'

#DATABASE = {
#    'dbname': 'avicudatos',
#    'user': 'postgres',
#    'password': 'qwerty',
#    'host': 'localhost',
#    'port': '5432'
#}
